# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

# application specific data

puts 'SETTING UP NOTIFICATIONS'
Notification.create! :name => 'Update vehicle info except milage'
Notification.create! :name => 'Cancel service'
Notification.create! :name => 'Postponed service'
Notification.create! :name => 'Due service'
Notification.create! :name => 'Overdue service', :required_intervals => true
Notification.create! :name => 'Completed booking'
Notification.create! :name => 'Date of booking'
Notification.create! :name => 'Pre booking reminder', :required_intervals => true
Notification.create! :name => 'Service date'
Notification.create! :name => 'Service information incomplete'
Notification.create! :name => 'Service done'
Notification.create! :name => 'Updated / Rescheduled service'

puts 'SETTING UP DEFAULT USER LOGIN'
user = User.create! :name => 'Administrator', :email => 'admin@example.com', 
                    :password => 'pa$$w0rd', :password_confirmation => 'pa$$w0rd', :approved => true, :admin => true
user.add_role :admin

